#!/usr/bin/python3
import sys

def first_prime_factor(n):
    for factor in [2, 3, 5, 7, 11]:
        if n % factor == 0:
            return factor
    i = 13
    while i * i <= n:
        if n % i == 0:
            return i
        i += 2
    return n

if __name__ == "__main__":
    with open(sys.argv[1], "r") as file:
        for line in file:
            num = int(line.strip())
            factor = first_prime_factor(num)
            print(f"{num}={num // factor}*{factor}")
